version: "3.8"
services:
  dropbase-client:
    image: dropbase/client:0.3.0.beta
    ports:
      - "3030:80"
  dropbase-server:
    image: dropbase/server:0.3.0.beta
    volumes:
      - ./workspace:/project/workspace
      - ./files:/project/files
      - ./config.toml:/project/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"
    # env_file:
    #   - .env
    environment:
      - PYTHONUNBUFFERED=1
      - HOST_WORKSPACE_PATH=${HOST_WORKSPACE_PATH}
      - REDIS_HOST=redis
  dropbase-lsp:
    image: dropbase/lsp:0.0.6
    volumes:
      - ./workspace:/project/workspace
      - ./files:/project/files
      # Attach custom volumes here
    ports:
      - "9095:9095"
    environment:
      - PYTHONUNBUFFERED=1
  redis:
    image: redis
    ports:
      - 6379:6379