version: "3.8"
services:
  dropbase-client:
    image: dropbase/client:0.2.7
    ports:
      - "3030:80"
  dropbase-server:
    image: dropbase/server:0.2.11
    volumes:
      - ./workspace:/project/workspace
      - ./files:/project/files
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - HOST_WORKSPACE_PATH=${HOST_WORKSPACE_PATH}
      - REDIS_HOST=redis
  dropbase-lsp:
    image: dropbase/lsp:0.0.6
    volumes:
      - ./workspace:/project/workspace
      - ./files:/project/files
      # Attach custom volumes here
    ports:
      - "9095:9095"
    environment:
      - PYTHONUNBUFFERED=1
  redis:
    image: redis
    ports:
      - 6379:6379