version: "3.8"
services:
  dropbase-client:
    image: dropbase/client:0.6.3
    ports:
      - "3030:80"
    depends_on:
      - dropbase-lsp
  dropbase-server:
    image: dropbase/server:0.6.0
    volumes:
      - ./workspace:/project/workspace
      - ./files:/project/files
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server.toml:/project/server.toml
    ports:
      - "9090:9090"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
  dropbase-lsp:
    image: dropbase/lsp:0.1.0
    volumes:
      - ./workspace:/project/workspace
      - ./files:/project/files
      - ./ruff.toml:/project/ruff.toml
      - /var/run/docker.sock:/var/run/docker.sock
      # Attach custom volumes here
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "9095:9095"
  redis:
    image: redis
    ports:
      - 6379:6379