version: "3.8"
services:
  dropbase-client:
    image: dropbase/client:0.0.6
    ports:
      - "3030:80"
  dropbase-server:
    image: dropbase/server:0.0.8
    volumes:
      - ./workspace:/project/workspace
      - ./requirements-custom.txt:/project/requirements-custom.txt
      # Attach custom volumes here
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
  dropbase-lsp:
    image: dropbase/lsp:0.0.5
    volumes:
      - ./workspace:/project/workspace
      # Attach custom volumes here
    ports:
      - "9095:9095"
    environment:
      - PYTHONUNBUFFERED=1