version: "3.8"
services:
  dropbase-server:
    image: dropbase/server:latest
    volumes:
      - ./workspace:/project/workspace
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
  dropbase-lsp:
    image: dropbase/lsp:latest
    volumes:
      - ./workspace:/project/workspace
    ports:
      - "9001:9001"
    environment:
      - PYTHONUNBUFFERED=1
  dropbase-client:
    image: dropbase/client:latest
    ports:
      - "3000:80"