version: "3.8"
services:
  dropbase-server:
    image: dropbase/server:latest
    volumes:
      - ./workspace:/project/workspace
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
  dropbase-lsp:
    image: dropbase/lsp:latest
    volumes:
      - ./workspace:/project/workspace
    ports:
      - "9095:9095"
    environment:
      - PYTHONUNBUFFERED=1
  dropbase-client:
    image: dropbase/client:latest
    ports:
      - "3030:80"