# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2023-12-01T22:37:28+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class WidgetsContext(BaseModel):
    pass


class Table1ColumnsContext(BaseModel):
    pass


class Table1Context(BaseModel):
    message: Optional[str] = Field(None, title='Message')
    message_type: Optional[str] = Field(None, title='Message Type')
    columns: Table1ColumnsContext


class TablesContext(BaseModel):
    table1: Table1Context


class Context(BaseModel):
    widgets: WidgetsContext
    tables: TablesContext
