# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2023-12-01T22:37:28+00:00

from __future__ import annotations

from pydantic import BaseModel


class WidgetsState(BaseModel):
    pass


class Table1State(BaseModel):
    pass


class TablesState(BaseModel):
    table1: Table1State


class State(BaseModel):
    widgets: WidgetsState
    tables: TablesState
