# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2024-08-02T23:10:25+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Table1ColumnsStore(BaseModel):
    order_id: Optional[int] = Field(None, title='Order Id')
    user_id: Optional[int] = Field(None, title='User Id')
    product_name: Optional[str] = Field(None, title='Product Name')
    quantity: Optional[int] = Field(None, title='Quantity')
    total_price: Optional[int] = Field(None, title='Total Price')
    order_date: Optional[str] = Field(None, title='Order Date')


class Table1UpdateRowStore(BaseModel):
    row_index: Optional[int] = Field(None, title='Row Index')
    old: Table1ColumnsStore
    new: Table1ColumnsStore


class Table1Store(BaseModel):
    add: Table1ColumnsStore
    update: Optional[List[Table1UpdateRowStore]] = Field([], title='Update')


class Store(BaseModel):
    table1: Optional[Table1Store] = None
