version: "3.8"
services:
  dropbase-server:
    extends:
      file: ../docker-compose.yml
      service: dropbase-server
    environment:
      - SOURCE_PG_DROPBASEDEMODB_HOST=demo-db
      - SOURCE_PG_DROPBASEDEMODB_DATABASE=dropbasedemodb
      - SOURCE_PG_DROPBASEDEMODB_USERNAME=demouser
      - SOURCE_PG_DROPBASEDEMODB_PASSWORD=demopass
      - SOURCE_PG_DROPBASEDEMODB_PORT=5432
  dropbase-lsp:
    extends:
      file: ../docker-compose.yml
      service: dropbase-lsp
  dropbase-client:
    extends:
      file: ../docker-compose.yml
      service: dropbase-client
  demo-db:
    build:
      context: demo
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=dropbasedemodb
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=demopass
